In [13]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline

In [14]:
data = pd.read_csv('data/unconv.csv')
data.head()

Well    Por  Perm    AI  Brittle   TOC    VR         Prod
0     1  12.08  2.92  2.80    81.40  1.16  2.31  4165.196191
1     2  12.38  3.53  3.22    46.17  0.89  1.88  3561.146205
2     3  14.02  2.59  4.01    72.80  0.89  2.72  4284.348574
3     4  17.67  6.75  2.63    39.81  1.08  1.88  5098.680869
4     5  17.52  4.57  3.18    10.94  1.51  1.90  3406.132832

In [15]:
Corr_matrix=data.corr()
Corr_matrix

Well       Por      Perm        AI   Brittle       TOC        VR  \
Well     1.000000  0.068927  0.077928  0.041483 -0.079252  0.022624 -0.007279   
Por      0.068927  1.000000  0.760546 -0.461549 -0.218570  0.711831  0.111860   
Perm     0.077928  0.760546  1.000000 -0.239636 -0.124017  0.471746  0.051023   
AI       0.041483 -0.461549 -0.239636  1.000000  0.127599 -0.531864  0.499143   
Brittle -0.079252 -0.218570 -0.124017  0.127599  1.000000 -0.214282  0.317929   
TOC      0.022624  0.711831  0.471746 -0.531864 -0.214282  1.000000  0.299483   
VR      -0.007279  0.111860  0.051023  0.499143  0.317929  0.299483  1.000000   
Prod     0.026817  0.861910  0.727426 -0.390835  0.237155  0.654445  0.323182   

             Prod  
Well     0.026817  
Por      0.861910  
Perm     0.727426  
AI      -0.390835  
Brittle  0.237155  
TOC      0.654445  
VR       0.323182  
Prod     1.000000

In [16]:
A = Corr_matrix.values
A

array([[ 1.        ,  0.06892651,  0.07792781,  0.04148262, -0.07925236,
         0.02262431, -0.00727868,  0.02681678],
       [ 0.06892651,  1.        ,  0.76054592, -0.46154937, -0.2185703 ,
         0.71183068,  0.11185978,  0.86190954],
       [ 0.07792781,  0.76054592,  1.        , -0.23963581, -0.1240173 ,
         0.47174632,  0.0510232 ,  0.72742614],
       [ 0.04148262, -0.46154937, -0.23963581,  1.        ,  0.12759943,
        -0.5318636 ,  0.49914265, -0.39083477],
       [-0.07925236, -0.2185703 , -0.1240173 ,  0.12759943,  1.        ,
        -0.21428177,  0.31792866,  0.23715533],
       [ 0.02262431,  0.71183068,  0.47174632, -0.5318636 , -0.21428177,
         1.        ,  0.29948287,  0.6544452 ],
       [-0.00727868,  0.11185978,  0.0510232 ,  0.49914265,  0.31792866,
         0.29948287,  1.        ,  0.32318155],
       [ 0.02681678,  0.86190954,  0.72742614, -0.39083477,  0.23715533,
         0.6544452 ,  0.32318155,  1.        ]])

In [17]:
C = np.corrcoef(A)
print('Rank:', np.linalg.matrix_rank(A))
print('Determinant: {:.7f}'.format(np.linalg.det(A)))
print(C)

Rank: 8
Determinant: 0.0007299
[[ 1.         -0.13004995 -0.13694199 -0.00782715 -0.33195796 -0.16394855
  -0.46666612 -0.30373867]
 [-0.13004995  1.          0.94416129 -0.88680523 -0.56508858  0.9227308
  -0.37934049  0.94112062]
 [-0.13694199  0.94416129  1.         -0.79948999 -0.550663    0.7910248
  -0.46540471  0.88142662]
 [-0.00782715 -0.88680523 -0.79948999  1.          0.36924234 -0.86481653
   0.56706352 -0.87811352]
 [-0.33195796 -0.56508858 -0.550663    0.36924234  1.         -0.53297446
   0.37647772 -0.25852206]
 [-0.16394855  0.9227308   0.7910248  -0.86481653 -0.53297446  1.
  -0.17605402  0.87982203]
 [-0.46666612 -0.37934049 -0.46540471  0.56706352  0.37647772 -0.17605402
   1.         -0.24774051]
 [-0.30373867  0.94112062  0.88142662 -0.87811352 -0.25852206  0.87982203
  -0.24774051  1.        ]]


In [18]:
X = data.drop('Prod', axis=1)
y = data['Prod'].values
index = ['intercept']+list(X.columns)
n = X.shape[0]
X = np.column_stack((np.ones(n), X))
w_hat = np.linalg.inv(X.T@X)@X.T@y
print(pd.Series(np.round(w_hat, 0), index=index))

intercept   -1232.0
Well            0.0
Por           230.0
Perm          116.0
AI           -365.0
Brittle        25.0
TOC           -78.0
VR            785.0
dtype: float64


In [19]:
x_new = np.array([1, 106, 15.32, 3.71, 3.29, 55.99, 1.35, 2.42])
y_new = 4748.315024
y_new_pred = x_new @ w_hat
print(np.round(np.abs(y_new_pred - y_new), 0))

from sklearn.metrics import mean_absolute_percentage_error
y_pred = X @ w_hat
print('Result MAPE {:.1f}:'.format(mean_absolute_percentage_error(y, y_pred)*100))

25.0
Result MAPE 3.6:


In [20]:
from sklearn.metrics import mean_absolute_percentage_error
X = data.drop(['Prod', 'Perm', 'TOC', 'Well'], axis=1)
y = data['Prod'].values
index = ['intercept']+list(X.columns)
n = X.shape[0]
X = np.column_stack((np.ones(n), X))
w_hat = np.linalg.inv(X.T@X)@X.T@y
y_pred = X @ w_hat
print(pd.Series(np.round(w_hat, 0), index=index))
print(f'MAPE: {mean_absolute_percentage_error(y, y_pred)*100:.5f} %')

intercept   -1835.0
Por           293.0
AI           -200.0
Brittle        28.0
VR            517.0
dtype: float64
MAPE: 4.04414 %


6.4 С помощью классического МНК найдите коэффициенты полиномиальной регрессии, если используется полином второй степени и задан фактор  и целевая переменная .

In [21]:
A = np.array([
    [1, 1, 1, 1],
    [1, 3, -2, 9],
    [1, 9, 4, 81]
]).T
y = np.array([3, 7, -5, 21])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat) 
# [2.4        0.46666667 0.13333333]

[ 0.11446013  2.46095638 -0.01608801]


In [22]:
# матрица наблюдений (включая столбец единиц)
A = np.array([
    [1, 1, 1, 1, 1],
    [5,9,4,3,5],
    [15,18,18,19,19],
    [7,6,7,7,7]
]).T
# вектор целевого признака
y = np.array([24, 22, 35, 33, 36])
# единичная матрица
E = np.eye(4)
# коэффициент регуляризации 
alpha = 1
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
w_hat_ridge = np.linalg.inv(A.T@A+alpha*E)@A.T@y
print(w_hat_ridge) 
## [0.6122449  0.29387755 0.5877551 ]

[-0.08523045 -1.70784126  1.91141216  0.7293992 ]
